window.dadDontLieInvitationGuests = {
    "ngo-nhat-truong": {
        "displayName": "Ngô Nhật Trường",
        "namePrefix": "diễn viên",
        "dearName": "diễn viên Ngô Nhật Trường",
        "showLetter": true,
        "letterTitle": "Mến gửi anh Trường,",
        "message": "Nghệ thuật là một hành trình độc hành, nên dù muốn hay không mỗi người đều sẽ phải cô đơn tự bước đi trên hành trình của mình. Nhưng điều đáng quý nhất của hành trình này là trên đường mình đi, mình được gặp những người bạn. Chân thành.\n\nVà anh là một người bạn như thế.\n\nAnh có một tâm hồn sâu lắng, ánh mắt nhiều suy tư và đượm buồn. Nhưng điều anh dành cho những người bạn của mình thì luôn là những điều tốt nhất mà anh có.\n\nNăm 2025 của em đã trở nên tuyệt vời biết bao khi em được gặp anh, được trở thành một người bạn của anh. Điều đó em luôn giữ trong lòng mà chưa bao giờ thật sự bày tỏ cho anh biết. Tệ.\n\nVới bộ phim của bọn mình, anh đã luôn dành cho nó tất cả tài năng, sự bao dung, sự yêu mến và lòng nhiệt thành. Không điều gì cảm động hơn được nhìn thấy diễn viên của mình trở thành nhân vật trên trường quay và sau đó là trên màn ảnh.\n\nHy vọng buổi chiếu sẽ khép lại hành trình của bộ phim này và mở ra những cơ hội mới trong tương lai.\n\nChân thành cảm ơn anh, với tất cả sự biết ơn và tình yêu dành cho một người diễn viên, và một người bạn.",
        "ticketName": "Ngô Nhật Trường",
        "ticketRole": "Diễn viên",
        "ticketDisplayName": "Diễn viên Ngô Nhật Trường",
        "role": "Diễn viên",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ngo-nhat-truong.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ngo-nhat-truong.mp4",
        "shareTitle": "Lời mời đến Ngô Nhật Trường",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "co-nhum": {
        "displayName": "Cô Nhum",
        "namePrefix": "diễn viên",
        "dearName": "diễn viên Cô Nhum",
        "showLetter": true,
        "letterTitle": "Mến gửi chị Nhum,",
        "message": "Ba năm trước, vào năm 2 đại học, em đã gặp chị ở Hộc Tủ. Ba năm sau, mình đã làm việc cùng nhau trong 2 bộ phim mà em tin là đã để lại trong lòng bọn mình những điều gì đó khó gọi tên.\n\nEm vẫn luôn ngưỡng mộ chị, không chỉ ở vai trò một diễn viên mà còn là một người mẹ kiên cường. Chị đã luôn cố gắng làm hai vai trò cùng lúc và em biết là chị đã không ít lần kiệt sức. Nhưng rồi em lại thấy chị đứng dậy, và dấn thân, và sống.\n\nChị là một diễn viên tài năng (không thể bàn cãi) nhưng trên tất cả chị còn là một người mẹ yêu thương con hết mực và cũng là một con người tử tế. Và em rất hạnh phúc vì trên hành trình học và làm phim, em đã được gặp chị, được làm việc với chị và được là một người bạn của chị.\n\nEm hy vọng, buổi chiếu phim sẽ khép lại hành trình của bộ phim này và mở ra những cơ hội mới cho cả hai bọn mình trong tương lai.\n\nChân thành cảm ơn chị, với tất cả sự biết ơn và ngưỡng mộ dành cho một người diễn viên, và một người mẹ.",
        "ticketName": "Cô Nhum",
        "ticketRole": "Diễn viên",
        "ticketDisplayName": "Diễn viên Cô Nhum",
        "role": "Diễn viên",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/co-nhum.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/co-nhum.mp4",
        "shareTitle": "Lời mời đến Cô Nhum",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-vu-uy-nhan": {
        "displayName": "Nguyễn Vũ Uy Nhân",
        "namePrefix": "diễn viên",
        "dearName": "diễn viên Nguyễn Vũ Uy Nhân",
        "showLetter": true,
        "letterTitle": "Mến gửi bé Bắp,",
        "message": "Mẹ Hà bảo với chú là chú dựng phim lâu đến nỗi mà Bắp lớn sắp cưới vợ luôn rồi 🙂‍↕️ Chú thấy có lỗi quá vì lúc nào chú cũng dựng phim lâu hết.\n\nNhưng mà bây giờ chú đã hoàn thành bộ phim này rồi, và chú rất vui để mời con đến xem bộ phim mà bọn mình cùng thực hiện.\n\nKhông nghi ngờ gì cả, Bắp là một diễn viên nhí tài năng. Hành trình làm bộ phim này cùng con khiến chú phá bỏ được một nỗi sợ muôn kiếp, là làm việc với một diễn viên nhí không hề khó khăn chút nào, mà còn là một hành trình vô cùng hạnh phúc.\n\nMong Bắp không giận chú vì chú hứa là sẽ đến nhà con để ăn cơm nhưng chú vẫn chưa có dịp.\n\nChú hy vọng, sau này con trưởng thành, con sẽ trở thành bất cứ ai mà con mong muốn. Một diễn viên, một đạo diễn, một quay phim,... hoặc thậm chí nếu lớn lên con lại đam mê đến bất kỳ một lĩnh vực nào khác ngoài phim ảnh, thì chú vẫn tin con sẽ luôn làm tốt nhất và làm giỏi nhất.\n\nChúc Bắp nhiều sức khỏe, và thành công hơn nữa trên hành trình mà con theo đuổi diễn xuất và phim ảnh.",
        "ticketName": "Nguyễn Vũ Uy Nhân",
        "ticketRole": "Diễn viên",
        "ticketDisplayName": "Diễn viên Nguyễn Vũ Uy Nhân",
        "role": "Diễn viên",
        "storyLine": "Trân quý mời con đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-vu-uy-nhan.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-vu-uy-nhan.mp4",
        "shareTitle": "Lời mời đến Nguyễn Vũ Uy Nhân",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "vu-nguyen-ngoc-ha": {
        "displayName": "Vũ Nguyễn Ngọc Hà",
        "namePrefix": "chị",
        "dearName": "chị Vũ Nguyễn Ngọc Hà",
        "showLetter": true,
        "letterTitle": "Gửi chị Vũ Nguyễn Ngọc Hà,",
        "message": "Em còn nhớ khi Sản xuất nói với em là đã mời được chị để trao đổi về phim, em đã rất hồi hộp. Phần vì em chưa bao giờ làm việc với diễn viên nhí trước đây, phần khác là em hơi lo chị sẽ không tin một đứa trẻ tuổi làm phim. Nhưng khi em được gặp chị và Bắp, em đã không còn bất kỳ nỗi lo nào nữa. Chị là một người mẹ tuyệt vời, và em nghĩ chị đã góp một phần rất lớn trên hành trình giúp Bắp trở thành một diễn viên giỏi.\n\nChân thành cảm ơn chị vì đã cho phép em được làm việc với Bắp. Chúc chị nhiều sức khỏe để tiếp tục đưa Bắp đi khắp nơi, xuất hiện trong mọi bộ phim hay khác.\n\nChúc chị và Bắp có trải nghiệm tốt khi xem phim.",
        "ticketName": "Vũ Nguyễn Ngọc Hà",
        "ticketRole": "Người mẹ quyền lực",
        "ticketDisplayName": "Người mẹ quyền lực Vũ Nguyễn Ngọc Hà",
        "role": "Người mẹ quyền lực",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/vu-nguyen-ngoc-ha.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/vu-nguyen-ngoc-ha.mp4",
        "shareTitle": "Lời mời đến Vũ Nguyễn Ngọc Hà",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "cha-bong": {
        "displayName": "Chà Bông",
        "namePrefix": "",
        "dearName": "Chà Bông",
        "showLetter": false,
        "letterTitle": "",
        "message": "",
        "ticketName": "Chà Bông",
        "ticketRole": "Người yêu",
        "ticketDisplayName": "Người yêu Chà Bông",
        "role": "Người yêu",
        "storyLine": "Trân quý mời em Bông đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/cha-bong.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/cha-bong.mp4",
        "shareTitle": "Lời mời đến Chà Bông",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-tung-lam": {
        "displayName": "Nguyễn Tùng Lâm",
        "namePrefix": "anh",
        "dearName": "anh Nguyễn Tùng Lâm",
        "showLetter": true,
        "letterTitle": "Gửi anh Nguyễn Tùng Lâm,",
        "message": "Cảnh báo: ngôn từ có khả năng nổi da gà và đầu độc đực rựa.\n\nĐược làm việc với anh là trải nghiệm tuyệt vời nhất em từng có khi làm phim. Em đã học hỏi được rất nhiều ở anh, đồng thời cũng tự phá bỏ được rất nhiều ảo tưởng và cứng nhắc của chính mình đối với phim ảnh. Có thể nói anh đã thay đổi cách em nghĩ về phim và làm phim.\n\nHy vọng mình sẽ có nhiều bộ phim nữa với nhau (trước khi nghỉ chơi). Em dám khẳng định, chỉ có 4 khả năng mà mình không còn làm chung nữa: một là em chết, hai là anh chết, ba là anh thấy em gà quá rồi không thích làm nữa, cuối cùng là anh chuyển qua làm đạo diễn toàn thời gian 🤓 Bằng không thì anh sẽ phải luôn quay tất cả các phim fiction của em.\n\nCảm ơn anh vì những trận cãi vã để em vỡ ra được nhiều điều. Cảm ơn anh vì trong quá trình làm việc, cho dù không còn mấy ai tin em thì anh vẫn luôn là người tin em nhất. Luôn cầm điện thoại lên và bắt đầu lock lại góc. Không than vãn, không một chút nghi ngờ. Và đó là điều em ngưỡng mộ ở anh bên cạnh tài năng của anh.\n\nEm nghĩ, cho dù anh làm bất cứ vai trò gì đi nữa, anh sẽ luôn làm ra những bộ phim tốt nhất và hay nhất. Và em chắc chắn sẽ là thằng duy nhất khen phim của anh nếu có một giả tưởng xấu số nào đó là không có bất cứ ai thích phim của anh hết :))))\n\nVững tin và tiến về phía trước. Chúc xem phim vui vẻ.",
        "ticketName": "Nguyễn Tùng Lâm",
        "ticketRole": "Cinematographer & Colorist",
        "ticketDisplayName": "Cinematographer & Colorist Nguyễn Tùng Lâm",
        "role": "Cinematographer & Colorist",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-tung-lam.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-tung-lam.mp4",
        "shareTitle": "Lời mời đến Nguyễn Tùng Lâm",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "hoang-bao-uyen": {
        "displayName": "Hoàng Bảo Uyên",
        "namePrefix": "chị",
        "dearName": "chị Hoàng Bảo Uyên",
        "showLetter": true,
        "letterTitle": "Mến gửi hờ bu,",
        "message": "Em viết cho nhiều người khác được vì em có sự xa lạ nhất định với họ, nhưng đến khi viết cho chị em cảm thấy hơi ngượng. Em suy đoán là do mình đã có những điều tương đối hiểu nhau, nên nếu em nói cái gì đó sến súa quá chị sẽ nhận ra ngay 🙂‍↕️\n\nEm biết bộ phim này đã để lại cho chị nhiều vết thương và không may thời điểm đó em đã không dũng cảm để an ủi chị và nói với chị là chị đã làm rất tốt. Lời nói dù có muộn màng nhưng trong thâm tâm em luôn ngưỡng mộ tài năng và tình yêu của chị dành cho phim ảnh.\n\nNếu có ai đó yêu phim hơn hờ bu thì người đó có thể là nhân vật trong phim chứ không có thật ngoài đời. Tình yêu của chị với phim ảnh, dù có kín đáo đến đâu cũng sẽ có một ngày tất cả mọi người đều nhìn thấy và cũng ngưỡng mộ nó giống em.\n\nHành trình mà bọn mình làm bạn và làm phim, với em hết sức quý giá. Em nghĩ đây chỉ là khởi đầu rất nhỏ của tình bạn này, mà sau này sẽ là những bộ phim khác nữa. Để khi bọn mình dù già nua, răng rụng trong khi nhai cháo thì mình cũng sẽ tự hào vì những gì đã đi qua, những gì mình đóng góp cho phim ảnh.\n\nChúc Uyên luôn luôn giữ được sự trong trẻo của mình với phim và thành công hơn trong vai trò mà chị đã chọn.\n\nNghỉ chơi khi nào thì chưa biết, nhưng chắc chắn phải đến xem phim cái đã. Thân.",
        "ticketName": "Hoàng Bảo Uyên",
        "ticketRole": "Art Director",
        "ticketDisplayName": "Art Director Hoàng Bảo Uyên",
        "role": "Art Director",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/hoang-bao-uyen.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/hoang-bao-uyen.mp4",
        "shareTitle": "Lời mời đến Hoàng Bảo Uyên",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "le-diem-quynh": {
        "displayName": "Lê Diễm Quỳnh",
        "namePrefix": "em",
        "dearName": "em Lê Diễm Quỳnh",
        "showLetter": true,
        "letterTitle": "Thân gửi Quỳnh Sun,",
        "message": "Gặp em cách đây 4 năm, anh chưa bao giờ nghĩ tình bạn này có thể đi xa đến vậy. Bọn mình đã trải qua cùng nhau nhiều điều đã làm bọn mình trưởng thành hơn và biết cách yêu phim ảnh hơn bất cứ điều gì tồn tại trên đời này.\n\nBộ phim này là một dấu mốc với anh, không phải vì anh làm nó đủ tốt. Nó chưa bao giờ được gọi là tốt cả nếu nói đến quá nhiều người làm phim tốt hơn ngoài kia. Nó đặc biệt với anh vì đây là bộ phim mà anh đã vượt lên chính mình và trở nên mạnh mẽ hơn, lý trí hơn nhưng cũng đồng thời biết cách yêu thương hơn.\n\nEm là một phần của bộ phim, là bạn anh và cũng là em gái của anh. Sau tất cả, bọn mình đã hoàn thành nó và có thể chiếu nó cho những người khác cùng xem.\n\nCảm ơn em đã luôn ủng hộ anh và luôn là một người bạn mà anh quý trọng rất nhiều.\n\nKhi nào nghỉ chơi thì chưa biết, nhưng cứ phải đến xem phim cái đã nhé.",
        "ticketName": "Lê Diễm Quỳnh",
        "ticketRole": "First Assistant Director",
        "ticketDisplayName": "First Assistant Director Lê Diễm Quỳnh",
        "role": "First Assistant Director",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/le-diem-quynh.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/le-diem-quynh.mp4",
        "shareTitle": "Lời mời đến Lê Diễm Quỳnh",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "kon-lon": {
        "displayName": "Kon Lớn",
        "namePrefix": "chị",
        "dearName": "chị Kon Lớn",
        "showLetter": true,
        "letterTitle": "Mến gửi chị Lớn,",
        "message": "Chân thành cảm ơn chị đã tin tưởng và nhận lời tham gia dự án phim của em. Mong rằng trải nghiệm của chị khi làm việc với em không quá tệ🙂‍↕️\n\nChúc chị có những giây phút xem phim vui vẻ. Cảm ơn chị Lớn một lần nữa.",
        "ticketName": "Kon Lớn",
        "ticketRole": "Second Assistant Director",
        "ticketDisplayName": "Second Assistant Director Kon Lớn",
        "role": "Second Assistant Director",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kon-lon.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kon-lon.mp4",
        "shareTitle": "Lời mời đến Kon Lớn",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "ho-minh-khoa": {
        "displayName": "Hồ Minh Khoa",
        "namePrefix": "em",
        "dearName": "em Hồ Minh Khoa",
        "showLetter": true,
        "letterTitle": "Gửi em Khoa",
        "message": "Chân thành cảm ơn Khoa đã tin tưởng và nhận lời tham gia dự án phim của anh. Mong rằng trải nghiệm của em khi làm việc với anh không quá tệ🙂‍↕️\n\nChúc em có những giây phút xem phim vui vẻ. Cảm ơn Khoa một lần nữa.",
        "ticketName": "Hồ Minh Khoa",
        "ticketRole": "Script Supervisor",
        "ticketDisplayName": "Script Supervisor Hồ Minh Khoa",
        "role": "Script Supervisor",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ho-minh-khoa.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ho-minh-khoa.mp4",
        "shareTitle": "Lời mời đến Hồ Minh Khoa",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "thuc-mai": {
        "displayName": "Thục Mai",
        "namePrefix": "chị",
        "dearName": "chị Thục Mai",
        "showLetter": true,
        "letterTitle": "Gửi chị Mai,",
        "message": "Em nhớ lúc em chưa có bất cứ thứ gì trong tay, kể cả kịch bản, thì người đầu tiên em nghĩ em có thể \"làm phiền\" được chính là chị. Có một khoảnh khắc lúc nói chuyện với thầy Sơn về kịch bản, em đã nghĩ ngay đến chị và sau khi gặp chị, điều em bất ngờ là chị đã tỏ ý muốn giúp em mặc dù em còn chưa có bất cứ thứ gì cả.\n\nBằng tất cả sự biết ơn, em đã cảm thấy rất may mắn, khi chị đã đứng ra quán xuyến toàn bộ dự án và tìm kiếm tất cả những đồng đội phù hợp cho dự án. Dù có rất nhiều vấn đề (mà hiển nhiên làm phim là giải quyết vấn đề) xảy ra giữa con người với con người, giữa con người với phim, và giữa tài chính với con người, thì chị đều đã giải quyết ổn thỏa. Em trân trọng tài năng, thời gian và sức khỏe mà chị đã bỏ ra cho dự án này.\n\nChân thành cảm ơn chị đã tin tưởng và nhận lời tham gia dự án phim của em. Và chúc cho buổi chiếu phim của bọn mình diễn ra suôn sẻ ✨🙂‍↕️",
        "ticketName": "Thục Mai",
        "ticketRole": "Producer & Post-Producer",
        "ticketDisplayName": "Producer & Post-Producer Thục Mai",
        "role": "Producer & Post-Producer",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/thuc-mai.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/thuc-mai.mp4",
        "shareTitle": "Lời mời đến Thục Mai",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "thao-quiengg": {
        "displayName": "Thảo Quiêngg",
        "namePrefix": "chị",
        "dearName": "chị Thảo Quiêngg",
        "showLetter": true,
        "letterTitle": "Gửi chị Quiêngg,",
        "message": "Được gặp chị ở workshop của chị Anh La hồi 2024, được nghe chị nói về quá trình làm Vùng Trũng, em cảm thấy rất ngưỡng mộ chị và điều bất ngờ hơn nữa là chị đã tin tưởng và nhận lời làm dự án của em.\n\nChân thành cảm ơn chị và Mai đã cùng đồng hành với em trong dự án lần này. Hy vọng trải nghiệm của chị khi làm bộ phim này với em không quá tệ 🙂‍↕️\n\nChúc chị nhiều sức khỏe để tiếp tục làm nhiều dự án phim hơn nữa và để chăm sóc cho bé Cá lớn nhanh cho chị sai vặt 😋",
        "ticketName": "Thảo Quiêngg",
        "ticketRole": "Co-Producer & Post-Producer",
        "ticketDisplayName": "Co-Producer & Post-Producer Thảo Quiêngg",
        "role": "Co-Producer & Post-Producer",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/thao-quiengg.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/thao-quiengg.mp4",
        "shareTitle": "Lời mời đến Thảo Quiêngg",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "be-ca": {
        "displayName": "Bé Cá",
        "namePrefix": "",
        "dearName": "Bé Cá",
        "showLetter": false,
        "letterTitle": "",
        "message": "",
        "ticketName": "Bé Cá",
        "ticketRole": "Diễn viên",
        "ticketDisplayName": "Diễn viên Bé Cá",
        "role": "Diễn viên",
        "storyLine": "Trân quý mời con đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/be-ca.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/be-ca.mp4",
        "shareTitle": "Lời mời đến Bé Cá",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "khuong-ngoc": {
        "displayName": "Khương Ngọc",
        "namePrefix": "chị",
        "dearName": "chị Khương Ngọc",
        "showLetter": true,
        "letterTitle": "Gửi chị Khương Ngọc,",
        "message": "Tổ sản xuất chắc là linh hồn của bộ phim này khi mà chỉ có 2 người đã có thể quán xuyến toàn bộ những thứ khó nhọc nhất trong suốt gần 2 tuần bấm máy. Em biết ơn chị vì đã tin tưởng và nhận lời tham gia dự án phim của em. Mong rằng trải nghiệm của chị khi làm việc với em không quá tệ 🙂‍↕️\n\nChân thành cảm ơn chị đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này.\n\nChúc chị có những giây phút xem phim vui vẻ. Cảm ơn Ngọc Lào một lần nữa.",
        "ticketName": "Khương Ngọc",
        "ticketRole": "Production Assistant",
        "ticketDisplayName": "Production Assistant Khương Ngọc",
        "role": "Production Assistant",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/khuong-ngoc.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/khuong-ngoc.mp4",
        "shareTitle": "Lời mời đến Khương Ngọc",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "vuong-linh": {
        "displayName": "Vương Linh",
        "namePrefix": "chị",
        "dearName": "chị Vương Linh",
        "showLetter": true,
        "letterTitle": "Gửi chị Vương Linh,",
        "message": "Tổ sản xuất chắc là linh hồn của bộ phim này khi mà chỉ có 2 người đã có thể quán xuyến toàn bộ những thứ khó nhọc nhất trong suốt gần 2 tuần bấm máy. Em biết ơn chị vì đã tin tưởng và nhận lời tham gia dự án phim của em. Mong rằng trải nghiệm của chị khi làm việc với em không quá tệ 🙂‍↕️\n\nChân thành cảm ơn chị đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này.\n\nChúc chị có những giây phút xem phim vui vẻ. Cảm ơn chị Linh một lần nữa.",
        "ticketName": "Vương Linh",
        "ticketRole": "Production Assistant",
        "ticketDisplayName": "Production Assistant Vương Linh",
        "role": "Production Assistant",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/vuong-linh.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/vuong-linh.mp4",
        "shareTitle": "Lời mời đến Vương Linh",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "dzuy-tom": {
        "displayName": "Dzuy Tom",
        "namePrefix": "anh",
        "dearName": "anh Dzuy Tom",
        "showLetter": true,
        "letterTitle": "Gửi anh Dzuy Tom,",
        "message": "Được gặp anh cách đây hơn một năm trong Tranh Kiếng Nhà Tôi, trong tâm thế còn thiếu kinh nghiệm, lần đầu tiên em được tận mắt thấy một người làm Art cực khổ và phải nhiều kinh nghiệm ra sao mới có thể gánh được toàn bộ một dự án.\n\nChân thành cảm ơn anh Duy đã dành rất nhiều tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ 🙂‍↕️\n\nChúc anh Duy nhiều sức khỏe để tiếp tục làm nhiều dự án hơn nữa, cưới 1 cô vợ, có 10 căn nhà mặt tiền và 100 tỷ tiền mặt trong tài khoản ✨",
        "ticketName": "Dzuy Tom",
        "ticketRole": "Production Designer",
        "ticketDisplayName": "Production Designer Dzuy Tom",
        "role": "Production Designer",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dzuy-tom.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dzuy-tom.mp4",
        "shareTitle": "Lời mời đến Dzuy Tom",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "ruby": {
        "displayName": "Ruby",
        "namePrefix": "em",
        "dearName": "em Ruby",
        "showLetter": true,
        "letterTitle": "Gửi em Ruby,",
        "message": "Chân thành cảm ơn em đã tin tưởng và nhận lời tham gia dự án phim của anh. Em đã cứu anh rất nhiều pha đi xuống lòng đất và không lời cảm ơn chân thành nào là đủ. Mong rằng trải nghiệm của em khi làm việc với anh không quá tệ🙂‍↕️\n\nChân thành cảm ơn em đã dành tài năng, thời gian và sức khỏe để cùng anh thực hiện bộ phim này.\n\nChúc em có những giây phút xem phim vui vẻ. Cảm ơn Ruby một lần nữa.",
        "ticketName": "Ruby",
        "ticketRole": "Production Designer's Assistant",
        "ticketDisplayName": "Production Designer's Assistant Ruby",
        "role": "Production Designer's Assistant",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ruby.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ruby.mp4",
        "shareTitle": "Lời mời đến Ruby",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nick-ng": {
        "displayName": "Nick Ng",
        "namePrefix": "anh",
        "dearName": "anh Nick Ng",
        "showLetter": true,
        "letterTitle": "Gửi anh Nick Ng,",
        "message": "Chân thành cảm ơn Nick đã tin tưởng và nhận lời tham gia dự án phim của em. Em biết tổ Art mình đã rất khổ sở và thiệt thòi. Có thể lời xin lỗi bây giờ là quá muộn, nhưng em hy vọng một lúc nào đó có thể bù đắp lại phần nào (nên cứ \"làm phiền\" em bất cứ khi nào anh cần:))\n\nChân thành cảm ơn anh đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này.\n\nChúc Nick có những giây phút xem phim vui vẻ. Cảm ơn Nick một lần nữa.",
        "ticketName": "Nick Ng",
        "ticketRole": "Set Designer",
        "ticketDisplayName": "Set Designer Nick Ng",
        "role": "Set Designer",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nick-ng.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nick-ng.mp4",
        "shareTitle": "Lời mời đến Nick Ng",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "kaii-khai-han": {
        "displayName": "Kaii Khải Hân",
        "namePrefix": "",
        "dearName": "Kaii Khải Hân",
        "showLetter": true,
        "letterTitle": "Gửi Kaii Khải Hân,",
        "message": "Chân thành cảm ơn Kaii đã tin tưởng và nhận lời tham gia dự án phim của em. Em biết tổ Art mình đã rất khổ sở và thiệt thòi. Có thể lời xin lỗi bây giờ là quá muộn, nhưng em hy vọng một lúc nào đó có thể bù đắp lại phần nào (nên cứ \"làm phiền\" em bất cứ khi nào Kai cần:))\n\nChân thành cảm ơn Kaii đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này.\n\nChúc Kaii có những giây phút xem phim vui vẻ. Cảm ơn Kaii một lần nữa.",
        "ticketName": "Kaii Khải Hân",
        "ticketRole": "Props Master",
        "ticketDisplayName": "Props Master Kaii Khải Hân",
        "role": "Props Master",
        "storyLine": "Trân quý mời Kaii đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kaii-khai-han.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kaii-khai-han.mp4",
        "shareTitle": "Lời mời đến Kaii Khải Hân",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "haibkk": {
        "displayName": "HaiBkk",
        "namePrefix": "em",
        "dearName": "em HaiBkk",
        "showLetter": true,
        "letterTitle": "Gửi em Hải,",
        "message": "Chân thành cảm ơn Hải đã tin tưởng và nhận lời tham gia dự án phim của anh. Anh biết tổ Art mình đã rất khổ sở và thiệt thòi. Có thể lời xin lỗi bây giờ là quá muộn, nhưng anh hy vọng một lúc nào đó có thể bù đắp lại phần nào (nên cứ \"làm phiền\" anh bất cứ khi nào em cần:))\n\nChân thành cảm ơn Hải đã dành tài năng, thời gian và sức khỏe để cùng anh thực hiện bộ phim này.\n\nChúc Hải có những giây phút xem phim vui vẻ. Cảm ơn Hải một lần nữa.",
        "ticketName": "HaiBkk",
        "ticketRole": "Set Decorator",
        "ticketDisplayName": "Set Decorator HaiBkk",
        "role": "Set Decorator",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/haibkk.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/haibkk.mp4",
        "shareTitle": "Lời mời đến HaiBkk",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "minh-thao": {
        "displayName": "Minh Thảo",
        "namePrefix": "chị",
        "dearName": "chị Minh Thảo",
        "showLetter": true,
        "letterTitle": "Gửi Minh Thảo,",
        "message": "Chân thành cảm ơn Thảo đã tin tưởng và nhận lời tham gia dự án phim của em. Em biết tổ Art mình đã rất khổ sở và thiệt thòi. Có thể lời xin lỗi bây giờ là quá muộn, nhưng em hy vọng một lúc nào đó có thể bù đắp lại phần nào (nên cứ \"làm phiền\" em bất cứ khi nào Thảo cần:))\n\nChân thành cảm ơn Thảo đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này.\n\nChúc Thảo có những giây phút xem phim vui vẻ. Cảm ơn Thảo một lần nữa.",
        "ticketName": "Minh Thảo",
        "ticketRole": "Wardrobe",
        "ticketDisplayName": "Wardrobe Minh Thảo",
        "role": "Wardrobe",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/minh-thao.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/minh-thao.mp4",
        "shareTitle": "Lời mời đến Minh Thảo",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "bia-huyen": {
        "displayName": "Bia Huyền",
        "namePrefix": "chị",
        "dearName": "chị Bia Huyền",
        "showLetter": true,
        "letterTitle": "Gửi chị Bia Huyền,",
        "message": "Chân thành cảm ơn chị Bia đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của chị khi làm việc với em không quá tệ🙂‍↕️\n\nChúc chị có những giây phút xem phim vui vẻ. Cảm ơn chị một lần nữa.",
        "ticketName": "Bia Huyền",
        "ticketRole": "Hair And Makeup Artist",
        "ticketDisplayName": "Hair And Makeup Artist Bia Huyền",
        "role": "Hair And Makeup Artist",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/bia-huyen.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/bia-huyen.mp4",
        "shareTitle": "Lời mời đến Bia Huyền",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "van-ngoc-thanh": {
        "displayName": "Văn Ngọc Thành",
        "namePrefix": "anh",
        "dearName": "anh Văn Ngọc Thành",
        "showLetter": true,
        "letterTitle": "Gửi anh Văn Ngọc Thành,",
        "message": "Chân thành cảm ơn anh Thành đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Văn Ngọc Thành",
        "ticketRole": "Focus Puller & Post-Production Supervisor",
        "ticketDisplayName": "Focus Puller & Post-Production Supervisor Văn Ngọc Thành",
        "role": "Focus Puller & Post-Production Supervisor",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/van-ngoc-thanh.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/van-ngoc-thanh.mp4",
        "shareTitle": "Lời mời đến Văn Ngọc Thành",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-kim-hau": {
        "displayName": "Nguyễn Kim Hậu",
        "namePrefix": "anh",
        "dearName": "anh Nguyễn Kim Hậu",
        "showLetter": true,
        "letterTitle": "Gửi anh Nguyễn Kim Hậu,",
        "message": "Chân thành cảm ơn anh Hậu đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Nguyễn Kim Hậu",
        "ticketRole": "Assistant Camera",
        "ticketDisplayName": "Assistant Camera Nguyễn Kim Hậu",
        "role": "Assistant Camera",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-kim-hau.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-kim-hau.mp4",
        "shareTitle": "Lời mời đến Nguyễn Kim Hậu",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "dang-xuan-hoang": {
        "displayName": "Đặng Xuân Hoàng",
        "namePrefix": "anh",
        "dearName": "anh Đặng Xuân Hoàng",
        "showLetter": true,
        "letterTitle": "Gửi anh Đặng Xuân Hoàng,",
        "message": "Chân thành cảm ơn anh Hoàng đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Đặng Xuân Hoàng",
        "ticketRole": "Assistant Camera",
        "ticketDisplayName": "Assistant Camera Đặng Xuân Hoàng",
        "role": "Assistant Camera",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dang-xuan-hoang.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dang-xuan-hoang.mp4",
        "shareTitle": "Lời mời đến Đặng Xuân Hoàng",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "khoa-too": {
        "displayName": "Khoa Too",
        "namePrefix": "anh",
        "dearName": "anh Khoa Too",
        "showLetter": true,
        "letterTitle": "Gửi anh Khoa Too,",
        "message": "Chân thành cảm ơn anh Khoa Too đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Khoa Too",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Khoa Too",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/khoa-too.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/khoa-too.mp4",
        "shareTitle": "Lời mời đến Khoa Too",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "gia-bao": {
        "displayName": "Gia Bảo",
        "namePrefix": "anh",
        "dearName": "anh Gia Bảo",
        "showLetter": true,
        "letterTitle": "Gửi anh Gia Bảo,",
        "message": "Chân thành cảm ơn anh Gia Bảo đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Gia Bảo",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Gia Bảo",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/giao-bao.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/giao-bao.mp4",
        "shareTitle": "Lời mời đến Gia Bảo",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "kii-tran": {
        "displayName": "Kii Trần",
        "namePrefix": "anh",
        "dearName": "anh Kii Trần",
        "showLetter": true,
        "letterTitle": "Gửi anh Kii Trần,",
        "message": "Chân thành cảm ơn anh Kii Trần đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Kii Trần",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Kii Trần",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kii-tran.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kii-tran.mp4",
        "shareTitle": "Lời mời đến Kii Trần",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "jason-ngo": {
        "displayName": "Jason Ngô",
        "namePrefix": "anh",
        "dearName": "anh Jason Ngô",
        "showLetter": true,
        "letterTitle": "Gửi anh Jason Ngô,",
        "message": "Chân thành cảm ơn anh Jason Ngô đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Jason Ngô",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Jason Ngô",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/jason-ngo.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/jason-ngo.mp4",
        "shareTitle": "Lời mời đến Jason Ngô",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-trung-hieu": {
        "displayName": "Nguyễn Trung Hiếu",
        "namePrefix": "anh",
        "dearName": "anh Nguyễn Trung Hiếu",
        "showLetter": true,
        "letterTitle": "Gửi anh Nguyễn Trung Hiếu,",
        "message": "Chân thành cảm ơn anh Hiếu đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Nguyễn Trung Hiếu",
        "ticketRole": "Key Grip",
        "ticketDisplayName": "Key Grip Nguyễn Trung Hiếu",
        "role": "Key Grip",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-trung-hieu.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-trung-hieu.mp4",
        "shareTitle": "Lời mời đến Nguyễn Trung Hiếu",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "crister-nguyen": {
        "displayName": "Crister Nguyen",
        "namePrefix": "anh",
        "dearName": "anh Crister Nguyen",
        "showLetter": true,
        "letterTitle": "Gửi anh Nguyên,",
        "message": "Chân thành cảm ơn anh Nguyên đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Crister Nguyen",
        "ticketRole": "Sound Operator",
        "ticketDisplayName": "Sound Operator Crister Nguyen",
        "role": "Sound Operator",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/crister-nguyen.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/crister-nguyen.mp4",
        "shareTitle": "Lời mời đến Crister Nguyen",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "ngo-xuan-ho": {
        "displayName": "Ngô Xuân Hồ",
        "namePrefix": "anh",
        "dearName": "anh Ngô Xuân Hồ",
        "showLetter": true,
        "letterTitle": "Gửi anh Ngô Xuân Hồ,",
        "message": "Chân thành cảm ơn anh Hồ đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trải nghiệm của anh khi làm việc với em không quá tệ🙂‍↕️\n\nChúc anh có những giây phút xem phim vui vẻ. Cảm ơn anh một lần nữa.",
        "ticketName": "Ngô Xuân Hồ",
        "ticketRole": "Sound Design & Re-recording Mixer",
        "ticketDisplayName": "Sound Design & Re-recording Mixer Ngô Xuân Hồ",
        "role": "Sound Design & Re-recording Mixer",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ngo-xuan-ho.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ngo-xuan-ho.mp4",
        "shareTitle": "Lời mời đến Ngô Xuân Hồ",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "huy-dep-trai": {
        "displayName": "Huy Đẹp Trai",
        "namePrefix": "anh",
        "dearName": "anh Huy Đẹp Trai",
        "showLetter": true,
        "letterTitle": "Gửi anh Huy,",
        "message": "Chắc anh là người biết em lâu nhất trong đoàn và còn là đồng hương. Em nhớ thời điểm đó, lần đầu em gặp anh ở quán Đen, em đã rất ngưỡng mộ anh. Mặc dù lúc đó em còn chưa biết phim ảnh là gì (và có thể giờ cũng chưa thật sự biết) em đã có một suy nghĩ lóe lên trong đầu là ước một ngày nào đó em có thể được làm chung với anh một dự án nào đó. Trong cái đầu non nớt của em lúc đó là như vậy. Và đúng 7 năm sau em đã được toại nguyện khi anh nhận lời cùng làm bộ phim này với em.\n\nAnh là một nghệ sĩ thật sự và em chưa từng gặp ai có nghệ sĩ tính rõ ràng được như anh. Cảm ơn anh đã dành tài năng, thời gian và sức khỏe để cùng em thực hiện bộ phim này. Mong rằng trong suốt quá trình làm việc với em, anh đã có những trải nghiệm không quá tệ 🙂‍↕️\n\nHy vọng sắp tới chuyến đi của anh thuận lợi và hy vọng anh em mình có thể cùng nhau làm thêm được nhiều dự án khác.",
        "ticketName": "Huy Đẹp Trai",
        "ticketRole": "Original Scores",
        "ticketDisplayName": "Original Scores Huy Đẹp Trai",
        "role": "Original Scores",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/huy-dep-trai.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/huy-dep-trai.mp4",
        "shareTitle": "Lời mời đến Huy Đẹp Trai",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "ha-tat-thanh": {
        "displayName": "Hà Tất Thành",
        "namePrefix": "anh",
        "dearName": "anh Hà Tất Thành",
        "showLetter": true,
        "letterTitle": "Gửi anh Hà Tất Thành,",
        "message": "Em Trí và em Mai thương mời anh Hà Tất Thành đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Hà Tất Thành",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Hà Tất Thành",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ha-tat-thanh.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ha-tat-thanh.mp4",
        "shareTitle": "Lời mời đến Hà Tất Thành",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "dang-thanh-tam": {
        "displayName": "Đặng Thành Tâm",
        "namePrefix": "anh",
        "dearName": "anh Đặng Thành Tâm",
        "showLetter": true,
        "letterTitle": "Gửi anh Đặng Thành Tâm,",
        "message": "Em Trí và Mai thương mời Tâm đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Đặng Thành Tâm",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Đặng Thành Tâm",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dang-thanh-tam.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dang-thanh-tam.mp4",
        "shareTitle": "Lời mời đến Đặng Thành Tâm",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-le-hoang-phuc": {
        "displayName": "Nguyễn Lê Hoàng Phúc",
        "namePrefix": "anh",
        "dearName": "anh Nguyễn Lê Hoàng Phúc",
        "showLetter": true,
        "letterTitle": "Gửi anh Hí,",
        "message": "Vào tháng 7 năm ngoái, sau khi bấm máy phim Buổi Công Chiếu, em đi phim này nè.\nĐây là bộ phim em nho nhỏ mà em làm cùng bé Mai, Phạm Hữu Trí, Lâm Nguyễn Tùng ... và rất nhiều em bé dễ thương khác nữa...\n\nĐây là một trong những kí ức đẹp của emmm.\nMong là anh sẽ enjoy chiếc phim này nhé!\n\nYêu,\nThảo Quiêngg",
        "ticketName": "Nguyễn Lê Hoàng Phúc",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Nguyễn Lê Hoàng Phúc",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-le-hoang-phuc.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-le-hoang-phuc.mp4",
        "shareTitle": "Lời mời đến Nguyễn Lê Hoàng Phúc",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-thien-an": {
        "displayName": "Nguyễn Thiên Ân",
        "namePrefix": "anh",
        "dearName": "anh Nguyễn Thiên Ân",
        "showLetter": true,
        "letterTitle": "Gửi Thiên Ân,",
        "message": "Thân mời bạn quý yêu của Quiêngg đến xem bộ phim ngắn nhỏ xinh này nhé.\nXin vía Cannes đến với gia đình BODND. \nĐây là chiếc phim nhẹ nhàng , yêu thương, mong bạn sẽ đến xem phim như là một buổi tối đi xem cùng gia đình nhaa!\n\nYêu,\nThảo Quiêngg",
        "ticketName": "Nguyễn Thiên Ân",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Nguyễn Thiên Ân",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-thien-an.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-thien-an.mp4",
        "shareTitle": "Lời mời đến Nguyễn Thiên Ân",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-ngoc-thao-ly": {
        "displayName": "Nguyễn Ngọc Thảo Ly",
        "namePrefix": "chị",
        "dearName": "chị Nguyễn Ngọc Thảo Ly",
        "showLetter": true,
        "letterTitle": "Gửi Thảo Ly,",
        "message": "Thân mời bạn quý yêu của Quiêngg đến xem bộ phim ngắn nhỏ xinh này nhé.\nXin vía Cannes đến với gia đình BODND. \nĐây là chiếc phim nhẹ nhàng , yêu thương, mong bạn sẽ đến xem phim như là một buổi tối đi xem cùng gia đình nhaa!\n\nYêu,\nThảo Quiêngg",
        "ticketName": "Nguyễn Ngọc Thảo Ly",
        "ticketRole": "Chị",
        "ticketDisplayName": "Chị Nguyễn Ngọc Thảo Ly",
        "role": "Chị",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-ngoc-thao-ly.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-ngoc-thao-ly.mp4",
        "shareTitle": "Lời mời đến Nguyễn Ngọc Thảo Ly",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "kha-bao": {
        "displayName": "Kha Bảo",
        "namePrefix": "anh",
        "dearName": "anh Kha Bảo",
        "showLetter": true,
        "letterTitle": "Gửi Kha Bảo,",
        "message": "Đây là bộ phim do Lâm Nguyễn Tùng DP, quay ở làng phong Quy Nhơn, nơi mà chẳng bao lâu nữa sẽ bị đập nát như chưa từng tồn tại. \nNhưng chắc chắn là những kỷ niệm quay phim ở đây sẽ còn quài, và những shot phim này cũng trở thành 1 phần lưu trữ những dấu vết cuối cùng của ngôi làng.\n\nMong em sẽ xem phim thật vuiiii nhé!\nYêu,\nThảo Quiêngg",
        "ticketName": "Kha Bảo",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Kha Bảo",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kha-bao.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kha-bao.mp4",
        "shareTitle": "Lời mời đến Kha Bảo",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "bi-bo": {
        "displayName": "Bi Bo",
        "namePrefix": "chị",
        "dearName": "chị Bi Bo",
        "showLetter": true,
        "letterTitle": "Gửi Bi Bo,",
        "message": "Đây là bộ phim do Lâm Nguyễn Tùng DP, quay ở làng phong Quy Nhơn, nơi mà chẳng bao lâu nữa sẽ bị đập nát như chưa từng tồn tại. \nNhưng chắc chắn là những kỷ niệm quay phim ở đây sẽ còn quài, và những shot phim này cũng trở thành 1 phần lưu trữ những dấu vết cuối cùng của ngôi làng.\n\nMong em sẽ xem phim thật vuiiii nhé!\nYêu,\nThảo Quiêngg",
        "ticketName": "Bi Bo",
        "ticketRole": "Chị",
        "ticketDisplayName": "Chị Bi Bo",
        "role": "Chị",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/bi-bo.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/bi-bo.mp4",
        "shareTitle": "Lời mời đến Bi Bo",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-thuy-thuy": {
        "displayName": "Nguyễn Thuý Thuý",
        "namePrefix": "chị",
        "dearName": "chị Nguyễn Thuý Thuý",
        "showLetter": true,
        "letterTitle": "Gửi chị Nguyễn Thuý Thuý,",
        "message": "Em Trí và em Mai thương mời chị Nguyễn Thuý Thuý đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Nguyễn Thuý Thuý",
        "ticketRole": "Chị",
        "ticketDisplayName": "Chị Nguyễn Thuý Thuý",
        "role": "Chị",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-thuy-thuy.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-thuy-thuy.mp4",
        "shareTitle": "Lời mời đến Nguyễn Thuý Thuý",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-luu-thanh-an": {
        "displayName": "Nguyễn Lưu Thanh An",
        "namePrefix": "anh",
        "dearName": "anh Nguyễn Lưu Thanh An",
        "showLetter": true,
        "letterTitle": "Gửi anh Nguyễn Lưu Thanh An,",
        "message": "Em Trí và em Mai thương mời anh Nguyễn Lưu Thanh An đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Nguyễn Lưu Thanh An",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Nguyễn Lưu Thanh An",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-luu-thanh-an.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-luu-thanh-an.mp4",
        "shareTitle": "Lời mời đến Nguyễn Lưu Thanh An",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "dao-nguyen-anh": {
        "displayName": "Đào Nguyên Anh",
        "namePrefix": "cô",
        "dearName": "cô Đào Nguyên Anh",
        "showLetter": true,
        "letterTitle": "Gửi cô Đào Nguyên Anh,",
        "message": "Em Trí và em Mai thương mời cô Đào Nguyên Anh đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Đào Nguyên Anh",
        "ticketRole": "Cô",
        "ticketDisplayName": "Cô Đào Nguyên Anh",
        "role": "Cô",
        "storyLine": "Trân quý mời cô đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dao-nguyen-anh.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dao-nguyen-anh.mp4",
        "shareTitle": "Lời mời đến Đào Nguyên Anh",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "song-mai": {
        "displayName": "Song Mai",
        "namePrefix": "em",
        "dearName": "em Song Mai",
        "showLetter": true,
        "letterTitle": "Gửi em Song Mai,",
        "message": "Chân thành cảm ơn sự có mặt của em trong buổi chiếu phim này. Hy vọng em sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.\n\nXin cảm ơn một lần nữa.",
        "ticketName": "Song Mai",
        "ticketRole": "Em",
        "ticketDisplayName": "Em Song Mai",
        "role": "Em",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/song-mai.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/song-mai.mp4",
        "shareTitle": "Lời mời đến Song Mai",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "sulla": {
        "displayName": "Sulla",
        "namePrefix": "chị",
        "dearName": "chị Sulla",
        "showLetter": true,
        "letterTitle": "Gửi chị Sulla,",
        "message": "Em Trí và em Mai thương mời chị Sulla đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Sulla",
        "ticketRole": "Chị",
        "ticketDisplayName": "Chị Sulla",
        "role": "Chị",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/sulla.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/sulla.mp4",
        "shareTitle": "Lời mời đến Sulla",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "nguyen-loc": {
        "displayName": "Nguyễn Lộc",
        "namePrefix": "anh",
        "dearName": "anh Nguyễn Lộc",
        "showLetter": true,
        "letterTitle": "Gửi anh Nguyễn Lộc,",
        "message": "Em Trí và em Mai thương mời anh Nguyễn Lộc đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Nguyễn Lộc",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Nguyễn Lộc",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-loc.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/nguyen-loc.mp4",
        "shareTitle": "Lời mời đến Nguyễn Lộc",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "dang-khoi": {
        "displayName": "Đăng Khôi",
        "namePrefix": "anh",
        "dearName": "anh Đăng Khôi",
        "showLetter": true,
        "letterTitle": "Gửi anh Đăng Khôi,",
        "message": "Em Trí và em Mai thương mời anh Đăng Khôi đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Đăng Khôi",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Đăng Khôi",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dang-khoi.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/dang-khoi.mp4",
        "shareTitle": "Lời mời đến Đăng Khôi",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "tuan-cao": {
        "displayName": "Tuấn Cao",
        "namePrefix": "anh",
        "dearName": "anh Tuấn Cao",
        "showLetter": true,
        "letterTitle": "Gửi anh Tuấn Cao,",
        "message": "Em Trí và em Mai thương mời anh Tuấn Cao đến và cùng xem \"Ba Ơi, Đừng Nói Dối\" tại buổi chiếu phim thân mật dành cho ekip và những bạn bè thân thương.",
        "ticketName": "Tuấn Cao",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Tuấn Cao",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/tuan-cao.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/tuan-cao.mp4",
        "shareTitle": "Lời mời đến Tuấn Cao",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "tran": {
        "displayName": "Trân",
        "namePrefix": "chị",
        "dearName": "chị Trân",
        "showLetter": true,
        "letterTitle": "Mến gửi chị Trân,",
        "message": "23 năm tồn tại của em chưa từng gặp một người sếp nào tệ, nhưng trong số đó chị là người sếp tuyệt vời nhất quả đất.\n\nCảm ơn cơ hội mà chị đã dành cho em, nếu không có công việc này, có thể em đã sống rất khổ sở và không thể nào trả nợ xong bộ phim này, và cũng không có dư dả thời gian để làm bộ phim một cách trọn vẹn.\n\nChân thành cảm ơn sự có mặt của chị trong buổi chiếu phim này. Hy vọng chị sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Trân",
        "ticketRole": "Chị",
        "ticketDisplayName": "Chị Trân",
        "role": "Chị",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/tran.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/tran.mp4",
        "shareTitle": "Lời mời đến Trân",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "ngoc-boi": {
        "displayName": "Ngọc Bội",
        "namePrefix": "cô",
        "dearName": "cô Ngọc Bội",
        "showLetter": true,
        "letterTitle": "Trân quý gửi cô Bội,",
        "message": "Có thể con còn quá non nớt và chưa suy nghĩ thấu đáo khi nói ra câu này, nhưng đối với con, cô là giáo viên duy nhất khiến con cảm thấy bản thân mình không quá tệ hại trong suốt 3 năm cấp ba.\n\nCon còn nhớ có lần con lên bục giảng để xin ý kiến của cô về ngành học của con. Cô đã luôn ân cần và thương mến con như vậy. Cô đã cho con rất nhiều niềm tin vào bản thân và một phần lý do khiến con có thể mạnh mẽ chọn học phim là nhờ sự động viên của cô.\n\nCon biết ơn cô vì trong thời gian \"tăm tối\" nhất của tuổi thành niên thì trước mắt con vẫn có một tia sáng le lói và cho con hy vọng. Người ta nói, mất đi hy vọng là mất đi tất cả. Cô nhỉ?\n\nThật hổ thẹn vì từ ngữ lủng củng và tối nghĩa. Hy vọng cô không trách con ehehehe🙂‍↕️\n\nSự xuất hiện của cô ở buổi chiếu phim chính là niềm vui của con. Mong cô sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.\n\nCon xin cảm ơn một lần nữa.",
        "ticketName": "Ngọc Bội",
        "ticketRole": "Cô",
        "ticketDisplayName": "Cô Ngọc Bội",
        "role": "Cô",
        "storyLine": "Trân quý mời cô đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/co-ngoc-boi.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/co-ngoc-boi.mp4",
        "shareTitle": "Lời mời đến Ngọc Bội",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "bao-dinh": {
        "displayName": "Bảo Định",
        "namePrefix": "diễn viên",
        "dearName": "diễn viên Bảo Định",
        "showLetter": true,
        "letterTitle": "Mến gửi anh Bảo Định,",
        "message": "Khi gần như tin rằng em đã hoàn thành việc dựng phim thì anh Định đã cho em những góp ý rất quý giá, khiến em tin là mình hoàn toàn có thể làm cho nó hay hơn nữa. Và em đã tiếp tục sửa phim thêm một lần nữa.\n\nVượt lên mọi cái tôi cá nhân vô nghĩa thì đọng lại trong bản phim \"mới\" là một cảm giác tĩnh đến lạ. Em đã thầm biết ơn vì em đủ dũng khí để xin góp ý từ anh. Và em đã thấy bộ phim đó hiện lên rõ nét hơn bao giờ hết.\n\nChân thành cảm ơn anh đã dành thời gian và những lời chân thành cho phim của em.\n\nSự xuất hiện của anh ở buổi chiếu phim chính là niềm vui của đoàn phim. Mong anh sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Bảo Định",
        "ticketRole": "Diễn viên",
        "ticketDisplayName": "Diễn viên Bảo Định",
        "role": "Diễn viên",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/bao-dinh.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/bao-dinh.mp4",
        "shareTitle": "Lời mời đến Bảo Định",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "minh-duc": {
        "displayName": "Minh Đức",
        "namePrefix": "thầy",
        "dearName": "thầy Minh Đức",
        "showLetter": true,
        "letterTitle": "Mến gửi thầy Đức,",
        "message": "Được gặp thầy chính là may mắn trong quá trình em học và trưởng thành trên hành trình làm phim.\n\nNhững bài học và phương pháp mà thầy truyền đạt đã giúp em rất nhiều trong công tác suy luận và thực hành với phim ảnh. Biết ơn thầy vì đã dành cho em những góp ý chân thành với bộ phim trước đó, và giờ là lúc để em giới thiệu với thầy bộ phim tiếp theo, mà em tin là đã có sự tiến bộ hơn một chút trong quá trình em học tập và thực hành.\n\nSự xuất hiện của thầy ở buổi chiếu phim chính là niềm vui của em. Mong thầy sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Minh Đức",
        "ticketRole": "Thầy",
        "ticketDisplayName": "Thầy Minh Đức",
        "role": "Thầy",
        "storyLine": "Trân quý mời thầy đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/minh-duc.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/minh-duc.mp4",
        "shareTitle": "Lời mời đến Minh Đức",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "kai": {
        "displayName": "Kai",
        "namePrefix": "em",
        "dearName": "em Kai",
        "showLetter": true,
        "letterTitle": "Mến gửi em Kai,",
        "message": "Chà Bông có kể cho anh về cảm nghĩ của em khi em xem bản phim Thầy Sơn's Cut ở trường, và anh thấy vui vì có người nhìn ra được một phần nào đó quá trình thực hành của anh đối với phim ảnh.\n\nCảm ơn Kai đã để ý và quan tâm đến trải nghiệm của anh, và anh muốn mời em đến xem bản Đi rét tờ cút của anh.\n\nAnh chúc hành trình làm phim tốt nghiệp của em suôn sẻ và hy vọng sau khi xong phim anh được xem phim của em.\n\nSự xuất hiện của em ở buổi chiếu phim chính là niềm vui của anh. Mong em sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Kai",
        "ticketRole": "Em",
        "ticketDisplayName": "Em Kai",
        "role": "Em",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kai.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/kai.mp4",
        "shareTitle": "Lời mời đến Kai",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "quoc-hung": {
        "displayName": "Quốc Hưng",
        "namePrefix": "em",
        "dearName": "em Quốc Hưng",
        "showLetter": true,
        "letterTitle": "Gửi em Quốc Hưng,",
        "message": "Trong suốt 3 năm được biết em, anh đã thấy được hành trình của em đã có rất nhiều khởi sắc. Và bất ngờ nhất chính là phim tốt nghiệp mà em bảo muốn kể cho anh với Uyên nghe, anh không ngờ nó lại hay đến vậy.\n\nHy vọng hành trình làm phim tốt nghiệp của em suôn sẻ và hy vọng sau khi xong phim, anh được xem phim của em.\n\nSự xuất hiện của em ở buổi chiếu phim chính là niềm vui của anh. Mong em sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Quốc Hưng",
        "ticketRole": "Em",
        "ticketDisplayName": "Em Quốc Hưng",
        "role": "Em",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/quoc-hung.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/quoc-hung.mp4",
        "shareTitle": "Lời mời đến Quốc Hưng",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "huy-hoang": {
        "displayName": "Huy Hoàng",
        "namePrefix": "em",
        "dearName": "em Huy Hoàng",
        "showLetter": true,
        "letterTitle": "Gửi em Huy Hoàng,",
        "message": "Chân thành cảm ơn sự có mặt của Hoàng trong buổi chiếu phim này. Hy vọng em sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.\n\nXin cảm ơn một lần nữa.",
        "ticketName": "Huy Hoàng",
        "ticketRole": "Em",
        "ticketDisplayName": "Em Huy Hoàng",
        "role": "Em",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/huy-hoang.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/huy-hoang.mp4",
        "shareTitle": "Lời mời đến Huy Hoàng",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "lam-anh": {
        "displayName": "Lâm Anh",
        "namePrefix": "",
        "dearName": "Lâm Anh",
        "showLetter": true,
        "letterTitle": "Trân quý gửi Lâm Anh,",
        "message": "Trong hành trình 5 năm từ lúc biết đến cái từ \"điện ảnh\", luôn có một Lâm Anh xuất hiện trong đó.\n\nTrong hành trình 5 năm từ lúc biết đến tình bạn, luôn có một Lâm Anh xuất hiện ở đó.\n\nTrong hành trình 5 năm học cách để yêu thương con người và chính mình, luôn có một Lâm Anh đồng hành.\n\nCảm ơn bạn đã đồng hành với tui từ khi còn chưa biết có cái nghề tên là đạo diễn, cho đến khi tui thật sự tốt nghiệp và có thể tự do thực hành điều mà mình mong muốn.\n\nSự xuất hiện của bạn ở buổi chiếu phim chính là hân hạnh của tui. Mong bạn sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Lâm Anh",
        "ticketRole": "",
        "ticketDisplayName": "Lâm Anh",
        "role": "",
        "storyLine": "Trân quý mời bạn đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/lam-anh.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/lam-anh.mp4",
        "shareTitle": "Lời mời đến Lâm Anh",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "phillip-cao": {
        "displayName": "Phillip Cao",
        "namePrefix": "đạo diễn",
        "dearName": "đạo diễn Phillip Cao",
        "showLetter": true,
        "letterTitle": "Gửi sếp Cao Phi,",
        "message": "Em từng có ác cảm với mấy ông sếp Quảng Cáo vì mấy ổng \"khó ưa\", nhưng anh là một ông sếp tuyệt vời nhất quả đất. Cảm ơn anh vì cơ hội công việc anh dành cho em, và mong sắp tới khi em đã hoàn thành quá trình với phim này, anh có thể cho em theo anh để làm trợ lý của anh tiếp.\n\nSự xuất hiện của anh ở buổi chiếu phim chính là hân hạnh của em. Mong anh sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Phillip Cao",
        "ticketRole": "Đạo diễn",
        "ticketDisplayName": "Đạo diễn Phillip Cao",
        "role": "Đạo diễn",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/phillip-cao.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/phillip-cao.mp4",
        "shareTitle": "Lời mời đến Phillip Cao",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "cao-phuong-uyen": {
        "displayName": "Cao Phương Uyên",
        "namePrefix": "đạo diễn",
        "dearName": "đạo diễn Cao Phương Uyên",
        "showLetter": true,
        "letterTitle": "Gửi chị Cao Phương Uyên,",
        "message": "Sự xuất hiện của chị ở buổi chiếu phim chính là hân hạnh của em. Hy vọng chị sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.\n\nEm xin cảm ơn một lần nữa.",
        "ticketName": "Cao Phương Uyên",
        "ticketRole": "Đạo diễn",
        "ticketDisplayName": "Đạo diễn Cao Phương Uyên",
        "role": "Đạo diễn",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/cao-phuong-uyen.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/cao-phuong-uyen.mp4",
        "shareTitle": "Lời mời đến Cao Phương Uyên",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "tuan-viet": {
        "displayName": "Tuấn Việt",
        "namePrefix": "",
        "dearName": "Tuấn Việt",
        "showLetter": true,
        "letterTitle": "Mến gửi Tuấn Việt,",
        "message": "Chân thành cảm ơn sự có mặt của Việt trong buổi chiếu phim này. Hy vọng bạn sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.\n\nMình xin cảm ơn một lần nữa.",
        "ticketName": "Tuấn Việt",
        "ticketRole": "",
        "ticketDisplayName": "Tuấn Việt",
        "role": "",
        "storyLine": "Trân quý mời bạn đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/tuan-viet.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/tuan-viet.mp4",
        "shareTitle": "Lời mời đến Tuấn Việt",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "remi-thomas": {
        "displayName": "Rémi Thomas",
        "namePrefix": "anh",
        "dearName": "anh Rémi Thomas",
        "showLetter": true,
        "letterTitle": "Mến gửi Rémi,",
        "message": "Cảm ơn Rémi vì đã dành thời gian để xem những bản dựng của em trong suốt quá trình em và anh Trường cùng dựng bộ phim này. Góp ý của anh, một cách trực tiếp, đã làm bộ phim hiện lên rõ ràng hơn bao giờ hết, và nếu không có nó bây giờ em đã có thể xem nó với một cảm giác chưa thể thỏa mãn được.\n\nSự xuất hiện của anh ở buổi chiếu phim chính là hân hạnh của em. Mong anh sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Rémi Thomas",
        "ticketRole": "Anh",
        "ticketDisplayName": "Anh Rémi Thomas",
        "role": "Anh",
        "storyLine": "Trân quý mời anh đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/remi-thomas.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/remi-thomas.mp4",
        "shareTitle": "Lời mời đến Rémi Thomas",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "vu-thi-hong": {
        "displayName": "Vũ Thị Hồng",
        "namePrefix": "cô",
        "dearName": "cô Vũ Thị Hồng",
        "showLetter": true,
        "letterTitle": "Trân quý gửi cô Hồng,",
        "message": "Cảm ơn cô đã có công sinh thành và nuôi dưỡng anh Trường. Như ảnh có từng nói, nếu không có tình yêu và sự giáo dục của cô thì giờ đây có thể cuộc đời ảnh đã rất khác.\n\nCon cảm ơn cô vì nếu không có cô, con đã không có anh Trường là một người bạn, và không có nhân vật Văn trong phim của con. Nên một cách gián tiếp, cô là lý do để nhân vật trong phim con tồn tại.\n\nCon vẫn nhớ có lần cô xem phim ở nhà anh Trường, mắt cô ướt đẫm và con nghĩ là phần nào đó con đã thành công vì khiến cho một khán giả có tuổi có thể đồng cảm được với bộ phim.\n\nCon xin phép mời cô đến buổi chiếu phim để được xem anh Trường trên màn ảnh rộng hơn. Sự xuất hiện của cô ở buổi chiếu phim chính là hân hạnh của con. Và mong rằng cô sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.",
        "ticketName": "Vũ Thị Hồng",
        "ticketRole": "Cô",
        "ticketDisplayName": "Cô Vũ Thị Hồng",
        "role": "Cô",
        "storyLine": "Trân quý mời cô đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/vu-thi-hong.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/vu-thi-hong.mp4",
        "shareTitle": "Lời mời đến Vũ Thị Hồng",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "ngoc-tram-anh": {
        "displayName": "Ngọc Trâm Anh",
        "namePrefix": "chị",
        "dearName": "chị Ngọc Trâm Anh",
        "showLetter": true,
        "letterTitle": "Mến gửi chị Mèo,",
        "message": "Sự xuất hiện của chị ở buổi chiếu phim chính là hân hạnh của em. Hy vọng chị sẽ có những trải nghiệm tốt trong suốt quá trình xem phim.\n\nEm xin cảm ơn một lần nữa.",
        "ticketName": "Ngọc Trâm Anh",
        "ticketRole": "Chị",
        "ticketDisplayName": "Chị Ngọc Trâm Anh",
        "role": "Chị",
        "storyLine": "Trân quý mời chị đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ngoc-tram-anh.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ngoc-tram-anh.mp4",
        "shareTitle": "Lời mời đến Ngọc Trâm Anh",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    },
    "ngoc-khue": {
        "displayName": "Ngọc Khuê",
        "namePrefix": "em trai",
        "dearName": "em trai Ngọc Khuê",
        "showLetter": false,
        "letterTitle": "",
        "message": "",
        "ticketName": "Ngọc Khuê",
        "ticketRole": "",
        "ticketDisplayName": "Ngọc Khuê",
        "role": "",
        "storyLine": "Trân quý mời em đến buổi chiếu phim thân mật",
        "introVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ngoc-khue.mp4",
        "storyVideoUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/invitation/intro/ngoc-khue.mp4",
        "shareTitle": "Lời mời đến Ngọc Khuê",
        "shareDescription": "Ba Ơi, Đừng Nói Dối",
        "shareImageUrl": "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2"
    }
};
if (window.dadDontLieInvitationConfig) {
    window.dadDontLieInvitationConfig.guests = window.dadDontLieInvitationGuests;
}
