window.dadDontLieInvitationConfig = {
    filmTitle: "Dad, Don't Lie",
    filmTitleVi: "Ba Ơi, Đừng Nói Dối",
    introFilmTitle: "Ba Ơi,\nĐừng Nói Dối",
    introSalutation: "Mến gửi",
    introStoryLine: "Trân quý mời anh đến buổi chiếu phim thân mật",
    hostName: "Pham Huu Tri",
    introVideoBaseUrl: "/short-films/dad-dont-lie/invitation/intro/",
    storyVideoBaseUrl: "/short-films/dad-dont-lie/invitation/intro/",
    introVideoUrl: "",
    fallbackStillUrl: "/short-films/dad-dont-lie/invitation/assets/poster.jpg",
    posterUrl: "/short-films/dad-dont-lie/invitation/assets/poster.jpg",
    ticketImageUrl: "/short-films/dad-dont-lie/invitation/assets/hero-image.jpg",
    secondaryTicketImageUrl: "/short-films/dad-dont-lie/invitation/assets/hero-image_2.jpeg",
    shareImageUrl: "https://assets.phamhuutri.com/assets/short-films/BODND/BODND_Still.jpeg?v=2",
    posterPlaceholderLabel: "",
    storyVideoUrl: "",
    storyImageUrl: "",
    fullInvitationVideoUrl: "",
    introPlaceholderLabel: "Intro video placeholder",
    eventDate: "T6, 21/08/2026",
    eventTime: "17:00",
    theaterName: "04",
    locationName: "DCINE Bến Thành - 6 Mạc Đĩnh Chi, Phường Sài Gòn, HCM",
    locationAddress: "",
    contactPhone: "0779706008",
    contactName: "Thục Mai",
    contactInfo: "0779706008 - Thục Mai",
    mapUrl: "https://maps.app.goo.gl/odFkyzn3RxUBbB9b8",
    note: "17:00 - 17:30: Đón khách\n17:30 - 18:30: Chiếu phim\n18:30 - 19:00: Giao lưu",
    noteCaption: "Có mặt đúng giờ để không bỏ lỡ bất cứ frame nào 🥸",
    guests: window.dadDontLieInvitationGuests || {}
};
