window.dadDontLieInvitationConfig = {
    filmTitle: "Dad, Don't Lie",
    filmTitleVi: "Ba Ơi, Đừng Nói Dối",
    introFilmTitle: "Ba Ơi,\nĐừng Nói Dối",
    introSalutation: "Mến gửi",
    introStoryLine: "Trân trọng mời anh đến buổi chiếu phim thân mật",
    hostName: "Pham Huu Tri",
    introVideoBaseUrl: "/short-films/dad-dont-lie/invitation/intro/",
    storyVideoBaseUrl: "/short-films/dad-dont-lie/invitation/intro/",
    introVideoUrl: "",
    fallbackStillUrl: "/short-films/dad-dont-lie/invitation/assets/poster.jpg",
    posterUrl: "/short-films/dad-dont-lie/invitation/assets/poster.jpg",
    ticketImageUrl: "/short-films/dad-dont-lie/invitation/assets/hero-image.jpg",
    secondaryTicketImageUrl: "/short-films/dad-dont-lie/invitation/assets/hero-image_2.jpeg",
    shareImageUrl: "/short-films/dad-dont-lie/invitation/assets/cover-image.jpeg",
    posterPlaceholderLabel: "",
    storyVideoUrl: "",
    storyImageUrl: "",
    fullInvitationVideoUrl: "",
    introPlaceholderLabel: "Intro video placeholder",
    eventDate: "T6, 21/08/2026",
    eventTime: "17:00",
    theaterName: "02",
    locationName: "DCINE Bến Thành - 6 Mạc Đĩnh Chi, Phường Sài Gòn, HCM",
    locationAddress: "",
    contactInfo: "0123456789",
    mapUrl: "https://maps.app.goo.gl/odFkyzn3RxUBbB9b8",
    note: "Vui lòng đến sớm 15 phút.",
    guests: window.dadDontLieInvitationGuests || {}
};
